sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t akhileldo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akhileldo/docker-react npm run test
